set(VCPKG_BUILD_TYPE release)

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)

if(PORT STREQUAL "icu")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_LINKER_FLAGS "-Wl,-headerpad_max_install_names" CACHE STRING "" FORCE)
